
export const items = [
    { id: Math.random(), title: 'Fitness', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '1', prix: ' 8 DH ', category: 'Sport', imgUrl: '1.png' },
    { id: Math.random(), title: 'Hacker ', description: 'Autocollants avec 100 motifs au choix .', pcs: '1', id: '2', prix: ' 6 DH ', category: 'Logo', imgUrl: '2.png' },
    { id: Math.random(), title: 'Emoji ', description: 'Autocollants avec 100 motifs au choix ', pcs: '200', id: '3', prix: ' 20 DH ', category: 'Logo', scor: 'Golde', imgUrl: '3.png' },
    { id: Math.random(), title: 'Among Us', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '4', prix: '6 DH ', category: 'Anime', imgUrl: '4.png' },
    { id: Math.random(), title: 'Tokyo Ghoul', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '5', prix: ' 5 DH ', category: 'Anime', imgUrl: '5.png' },
    { id: Math.random(), title: 'Dragonball Z', description: 'Autocollants avec 100 motifs au choix ', pcs: '7', id: '6', prix: ' 18 DH ', category: 'Anime', imgUrl: '6.png' },
    { id: Math.random(), title: 'Dragonball', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '7', prix: ' 12 DH ', category: 'Anime', imgUrl: '7.png' },
    { id: Math.random(), title: 'One Piece', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '8', prix: ' 12 DH', category: 'Anime', imgUrl: '8.png' },
    { id: Math.random(), title: 'Anime', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '9', prix: '16 DH ', category: 'Anime', imgUrl: '9.png' },
    { id: Math.random(), title: 'Tokyo Ghoul', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '10', prix: ' 8 DH ', category: 'Anime', imgUrl: '10.png' },
    { id: Math.random(), title: 'Diable Dragon', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '11', prix: '4 DH ', category: 'Anime', imgUrl: '11.png' },
    { id: Math.random(), title: 'Super-Héros', description: 'Autocollants avec 100 motifs au choix  ', pcs: '1', id: '12', prix: ' 12 DH ', category: 'Anime', imgUrl: '12.png' },
    { id: Math.random(), title: 'Le démon a ri', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '13', prix: ' 3 DH ', category: 'Anime', imgUrl: '13.png' },
    { id: Math.random(), title: 'Fille Ninja', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '14', prix: ' 5 DH ', category: 'Anime', imgUrl: '14.png' },
    { id: Math.random(), title: 'Attack Titan', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '15', prix: '5 DH ', category: 'Anime', imgUrl: '15.png' },
    { id: Math.random(), title: 'Naruto', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '16', prix: ' 8 DH ', category: 'Anime', imgUrl: '16.png' },
    { id: Math.random(), title: 'Nuageux', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '17', prix: '3 DH ', category: 'Logo', imgUrl: '17.png' },
    { id: Math.random(), title: 'Roronoa Zoro', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '18', prix: '8 DH ', category: 'Anime', imgUrl: '18.png' },
    { id: Math.random(), title: 'Note Musique', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '19', prix: '2 DH', category: 'Logo', imgUrl: '19.png' },
    { id: Math.random(), title: 'Black Army', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '20', prix: '5 DH ', category: 'Sport', imgUrl: '20.png' },
    { id: Math.random(), title: 'Green Boys ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '21', prix: '5 DH', category: 'Sport', imgUrl: '21.png' },
    { id: Math.random(), title: 'Winners ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '22', prix: '5 DH', category: 'Sport', imgUrl: '22.png' },
    { id: Math.random(), title: 'Real Madrid', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '23', prix: '5 DH', category: 'Sport', imgUrl: '23.png' },
    { id: Math.random(), title: 'Barcelona ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '24', prix: '5 DH', category: 'Sport', imgUrl: '24.png' },
    { id: Math.random(), title: 'Paris Saint-', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '25', prix: '5 DH', category: 'Sport', imgUrl: '25.png' },
    { id: Math.random(), title: 'Juventus', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '26', prix: '5 DH', category: 'Sport', imgUrl: '26.png' },
    { id: Math.random(), title: 'I Love Boxing', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '27', prix: '3 DH', category: 'Sport', imgUrl: '27.png' },
    { id: Math.random(), title: 'Titan', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '28', prix: '4 DH', category: 'Anime', imgUrl: '28.png' },
    { id: Math.random(), title: 'Love', description: 'Autocollants avec 100 motifs au choix', pcs: '2', id: '29', prix: '2 DH', category: 'Logo', imgUrl: '29.png' },
    { id: Math.random(), title: 'Pop smok', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: ' 30', prix: '4 DH', category: 'Logo', imgUrl: '30.png' },
    { id: Math.random(), title: 'Dragon Ball Z ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: ' 31', prix: '5 DH', category: 'Anime', imgUrl: '31.png' },
    { id: Math.random(), title: 'Itachi Uchiha ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: ' 32', prix: '5 DH', category: 'Anime', imgUrl: '32.png' },
    { id: Math.random(), title: 'Kengan ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: ' 33', prix: '4 DH', category: 'Anime', imgUrl: '33.png' },
    { id: Math.random(), title: 'Science ', description: 'Autocollants avec 100 motifs au choix ', pcs: '24', id: ' 34', prix: '18 DH', category: 'Logo', imgUrl: '34.png' },
    { id: Math.random(), title: 'Dragon  ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '35', prix: '4 DH', category: 'Logo', imgUrl: '35.png' },
    { id: Math.random(), title: 'Happy  ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '36', prix: '5 DH', category: 'Logo', imgUrl: '36.png' },
    { id: Math.random(), title: 'Filistin ', description: 'Autocollants avec 100 motifs au choix ', pcs: '25', id: '37', prix: '12 DH', category: 'Logo', imgUrl: '37.png' },
    { id: Math.random(), title: 'LCDP', description: 'Autocollants avec 100 motifs au choix ', pcs: '25', id: '38', prix: '12 DH', category: 'Logo', imgUrl: '38.png' },
    { id: Math.random(), title: ' Gym', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '39', prix: '4 DH', category: 'Sport', imgUrl: '39.png' },
    { id: Math.random(), title: 'Eid Mubarak ', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '40', prix: '3 DH', category: 'Logo', imgUrl: '40.png' },
    { id: Math.random(), title: 'Yamaha', description: 'Autocollants avec 100 motifs au choix ', pcs: '2', id: '41', prix: '4 DH', category: 'Logo', imgUrl: '41.png' },
    { id: Math.random(), title: 'Marijuana', description: 'Autocollants avec 100 motifs au choix', pcs: '8', id: '42', prix: '8 DH', category: 'Logo', imgUrl: '42.png' },
    { id: Math.random(), title: 'Sister', description: 'Autocollants avec 100 motifs au choix ', pcs: '2', id: '43', prix: '3 DH', category: 'Logo', imgUrl: '43.png' },
    { id: Math.random(), title: ' Snoop Dogg', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '44', prix: '3 DH', category: 'Logo', imgUrl: '44.png' },
    { id: Math.random(), title: 'I Love Mom', description: 'Autocollants avec 100 motifs au choix ', pcs: '2', id: '45', prix: '3 DH', category: 'Logo', imgUrl: '45.png' },
    { id: Math.random(), title: 'Med Salah', description: 'Autocollants avec 100 motifs au choix ', pcs: '1', id: '46', prix: '4 DH', category: 'Sport', imgUrl: '46.png' },
    { id: Math.random(), title: 'Cristiano ', description: 'Autocollants avec 100 motifs au choix', pcs: '2', id: '47', prix: '4 DH', category: 'Sport', imgUrl: '47.png' },
    { id: Math.random(), title: 'Einstein ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '48', prix: '3 DH', category: 'Logo', imgUrl: '48.png' },
    { id: Math.random(), title: ' i love you', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '49', prix: '3 DH', category: 'Logo', imgUrl: '49.png' },
    { id: Math.random(), title: 'Ronaldinho ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '50', prix: '4 DH', category: 'Sport', imgUrl: '50.png' },
    { id: Math.random(), title: 'Dragon Ball Z', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '51', prix: '6 DH', category: 'Anime', imgUrl: '51.png' },
    { id: Math.random(), title: 'Kung fu', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '52', prix: '3 DH', category: 'Sport', imgUrl: '52.png' },
    { id: Math.random(), title: 'Neymar ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '53', prix: '4 DH', category: 'Sport', imgUrl: '53.png' },
    { id: Math.random(), title: 'love football ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '54', prix: '3 DH', category: 'Sport', imgUrl: '54.png' },
    { id: Math.random(), title: 'King / Queen', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '55', prix: '5 DH', category: 'Logo', imgUrl: '55.png' },
    { id: Math.random(), title: 'Amazigh', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '56', prix: '3 DH', category: 'Logo', imgUrl: '56.png' },
    { id: Math.random(), title: 'Sbh lkhir', description: 'Autocollants avec 100 motifs au choix', pcs: '3', id: '57', prix: '2 DH', category: 'Logo', imgUrl: '57.png' },
    { id: Math.random(), title: 'Bad Boy ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '58', prix: '3 DH', category: 'Logo', imgUrl: '58.png' },
    { id: Math.random(), title: 'Garu ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '59', prix: '5 DH', category: 'Anime', imgUrl: '59.png' },
    { id: Math.random(), title: 'Love Amazigh', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '60', prix: '3 DH', category: 'Logo', imgUrl: '60.png' },
    { id: Math.random(), title: 'Dragon', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '61', prix: '3 DH', category: 'Anime', imgUrl: '61.png' },
    { id: Math.random(), title: 'Cobra', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '62', prix: '3 DH', category: 'Anime', imgUrl: '62.png' },
    { id: Math.random(), title: 'Papillon', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '63', prix: '3 DH', category: 'Logo', imgUrl: '63.png' },
    { id: Math.random(), title: 'Atomic Shinobi', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '64', prix: '5 DH', category: 'Anime', imgUrl: '64.png' },
    { id: Math.random(), title: 'Sharingan', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '65', prix: '3 DH', category: 'Anime', imgUrl: '65.png' },
    { id: Math.random(), title: 'BMW', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '66', prix: '3 DH', category: 'Sport', imgUrl: '66.png' },
    { id: Math.random(), title: 'Rolls Royce', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '67', prix: '5 DH', category: 'Sport', imgUrl: '67.png' },
    { id: Math.random(), title: 'Fitness', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '68', prix: '2 DH', category: 'Sport', imgUrl: '68.png' },
    { id: Math.random(), title: 'i love you', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '69', prix: '2 DH', category: 'Logo', imgUrl: '69.png' },
    { id: Math.random(), title: 'Halloween', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '70', prix: '3 DH', category: 'Logo', imgUrl: '70.png' },
    { id: Math.random(), title: 'Kakashi', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '71', prix: '3 DH', category: 'Logo', imgUrl: '71.png' },
    { id: Math.random(), title: 'forehead kiss', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '72', prix: '4 DH', category: 'Logo', imgUrl: '72.png' },
    { id: Math.random(), title: 'Money Bag', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '73', prix: '3 DH', category: 'Logo', imgUrl: '73.png' },
    { id: Math.random(), title: 'Promesse rose', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '74', prix: '2 DH', category: 'Logo', imgUrl: '74.png' },
    { id: Math.random(), title: 'CASH MONEY', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '75', prix: '3 DH', category: 'Logo', imgUrl: '75.png' },
    { id: Math.random(), title: 'Bad Boy ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '76', prix: '3 DH', category: 'Logo', imgUrl: '76.png' },
    { id: Math.random(), title: 'Hacker ', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '77', prix: '3 DH', category: 'Logo', imgUrl: '77.png' },
    { id: Math.random(), title: 'informatique', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '78', prix: '3 DH', category: 'Logo', imgUrl: '78.png' },
    { id: Math.random(), title: 'Millionaire', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '79', prix: '3 DH', category: 'Logo', imgUrl: '79.png' },
    { id: Math.random(), title: 'Bentley', description: 'Autocollants avec 100 motifs au choix', pcs: '1', id: '80', prix: ' DH', category: 'Sport', imgUrl: '80.png' },








]
